### ISSUE TITLE
Highlight Bot Offline

### ISSUE THREAD

**Issue by kristianserrano** [iomintz/highlight-bot#11]
It seems the Highlight Bot is offline now.

**Comment by ioistired** [comment]
Yeah, it's currently offline because the bot wasn't performing its main functionality, so it didn't make sense to leave it online and mislead users into thinking it was working. I still haven't gotten around to fixing it. I'll leave this issue open as a reminder.

**Comment by kristianserrano** [comment]
Ah, OK. Thank you. Several in my community servers were assuming it wasn't working because it was offline. I'll let them know.

**Comment by ioistired** [comment]
Fixed
