### ISSUE TITLE
Highlight word or phrase is too small.

### ISSUE THREAD

**Issue by RudeySH** [iomintz/highlight-bot#8]
Is there a technical reason the bot doesn't allow me to add a two-letter acronym? It would be really useful for me, I run a site and people mostly refer to it as `SH`. This is why I'm hoping the Highlight bot could be updated so that it allows us to add short words.

**Comment by RudeySH** [comment]
Whoops, my bad, closed by accident.

**Comment by ioistired** [comment]
Fixed and deployed.
